# `Sample.xlsx` was downloaded from https://ngdc.cncb.ac.cn/methbank/samples?q=HRA000099

wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_N0M1b_WT_N487_82yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_NAN0M0_InFrameDel_N612_77yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_NAN0M0_WT_N659_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T0N0M0_WT_N332_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1aN0M0_WT_N367_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1aN0M0_WT_N6_59yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1aN0M1b_WT_N236_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1bN0M0_InFrameDel_N312_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1bN0M0_InFrameDel_N358_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1bN0M0_WT_N265_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1bN0M0_WT_N273_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1bN0M0_WT_N393_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_FrameShiftDel_N133_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_FrameShiftDel_N182_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_FrameShiftDel_N482_77yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N162_60yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N176_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N216_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N329_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N335_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N361_60yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N378_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N600_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_InFrameDel_N727_60yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_MissenseMutation_N210_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_MissenseMutation_N213_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_MissenseMutation_N321_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_MissenseMutation_N380_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_MissenseMutation_N565_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_MissenseMutation_N576_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_MissenseMutation_N592_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N117_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N120_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N123_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N160_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N186_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N198_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N19_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N229_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N313_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N314_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N318_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N32_88yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N385_58yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N396_58yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N405_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N431_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N498_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N50_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N512_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N515_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N52_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N577_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N62_56yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N78_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M0_WT_N96_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M1b_InFrameDel_N609_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN0M1b_WT_N513_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T1cN1M0_WT_N476_55yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_FrameShiftIns_N471_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N157_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N232_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N289_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N326_63yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N408_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N58_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N613_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N716_53yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_InFrameDel_N92_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_MissenseMutation_N202_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_MissenseMutation_N215_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_MissenseMutation_N587_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N132_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N143_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N209_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N22_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N231_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N251_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N258_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N283_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N319_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N331_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N34_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N391_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N434_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N473_59yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N551_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N556_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N595_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N597_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M0_WT_N643_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M1b_InFrameDel_N36_77yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M1b_MissenseMutation_N607_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M1b_WT_N131_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0M1b_WT_N611_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0Mx_InFrameDel_N558_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0Mx_MissenseMutation_N563_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0Mx_NonsenseMutation_N521_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2aN0Mx_WT_N411_63yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_FrameShiftDel_N339_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_FrameShiftDel_N480_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_InFrameDel_N109_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_MissenseMutation_N26_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_MissenseMutation_N271_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N100_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N10_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N16_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N196_59yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N294_54yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N379_80yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N384_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N465_80yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M0_WT_N54_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0M1b_InFrameDel_N63_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN0Mx_WT_N18_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN1M0_WT_N42_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2bN1M0_WT_N477_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_FrameShiftDel_N250_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_FrameShiftDel_N315_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N111_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N12_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N167_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N17_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N208_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N330_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N340_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N60_77yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_InFrameDel_N64_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_MissenseMutation_N325_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_MissenseMutation_N349_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_MissenseMutation_N53_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_MissenseMutation_N56_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_MissenseMutation_N57_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N114_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N124_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N137_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N279_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N334_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N373_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N375_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N43_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N467_56yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N47_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N574_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N578_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N685_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M0_WT_N717_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M1b_MissenseMutation_N608_50yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0M1b_WT_N185_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN0Mx_InFrameDel_N410_80yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN1M0_WT_N585_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN1M1b_InFrameDel_N211_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2cN1M1b_WT_N491_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2N0M0_MissenseMutation_N508_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2N0M0_WT_N178_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2N0M0_WT_N509_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T2N0M0_WT_N546_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_Frame_Shift_Del_N85_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_InFrameDel_N113_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_InFrameDel_N300_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_InFrameDel_N728_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_MissenseMutation_N1_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_WT_N172_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_WT_N268_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_WT_N342_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_WT_N389_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_WT_N61_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN0M0_WT_N72_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN1M0_WT_N201_55yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN1M0_WT_N217_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aN1M1a_WT_N69_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3aNXM0_InFrameDel_N31_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN0M0_MissenseMutation_N139_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN0M0_WT_N103_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN0M0_WT_N286_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN0M0_WT_N496_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN0M0_WT_N605_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN0M1b_InFrameDel_N174_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN0M1b_WT_N502_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN1M0_WT_N125_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN1M0_WT_N67_51yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN1M1a_FrameShiftDel_N28_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bN1M1c_WT_N166_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bNAM0_WT_N637_57yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3bNxM0_WT_N729_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3cN0M0_WT_N71_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Normal_Prostate_T3NAM0_WT_N638_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_NAN0M0_InFrameDel_T612_77yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_NAN0M0_WT_T659_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_NAN0M1b_WT_T487_82yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_NANANA_NA_T274_NAyrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T0N0M0_WT_T332_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1aN0M0_WT_T367_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1aN0M0_WT_T6_59yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1aN0M1b_WT_T236_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1bN0M0_InFrameDel_T312_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1bN0M0_WT_T265_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1bN0M0_WT_T273_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1bN0M0_WT_T393_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_Frame_Shift_Del_T133_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_Frame_Shift_Del_T182_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_FrameShiftDel_T482_77yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T120_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T162_60yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T176_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T216_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T329_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T335_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T361_60yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T378_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T600_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_InFrameDel_T727_60yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_Missense_Mutation_T592_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_MissenseMutation_T210_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_MissenseMutation_T213_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_MissenseMutation_T321_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_MissenseMutation_T380_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_MissenseMutation_T565_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_MissenseMutation_T576_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T117_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T123_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T160_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T186_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T198_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T19_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T229_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T313_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T314_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T32_88yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T385_58yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T396_58yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T405_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T431_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T498_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T50_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T512_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T515_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T52_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T577_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T62_56yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T78_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M0_WT_T96_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M1b_InFrameDel_T609_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN0M1b_WT_T513_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T1cN1M0_WT_T476_55yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_FrameShiftIns_T471_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T157_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T232_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T289_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T326_63yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T408_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T58_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T613_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T716_53yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_InFrameDel_T92_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_MissenseMutation_T202_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_MissenseMutation_T215_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_MissenseMutation_T587_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T132_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T143_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T209_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T22_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T231_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T251_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T258_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T283_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T319_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T331_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T34_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T391_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T434_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T473_59yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T551_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T556_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T595_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T597_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M0_WT_T643_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M1b_InFrameDel_T36_77yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M1b_MissenseMutation_T607_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M1b_WT_T131_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0M1b_WT_T611_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0Mx_InFrameDel_T558_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0Mx_Missense_Mutation_T563_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0Mx_NonsenseMutation_T521_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2aN0Mx_WT_T411_63yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_FrameShiftDel_T339_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_FrameShiftDel_T480_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_InFrameDel_T109_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_InFrameDel_T358_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_MissenseMutation_T26_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_MissenseMutation_T271_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T100_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T10_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T16_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T196_59yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T294_54yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T379_80yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T384_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T465_80yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M0_WT_T54_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0M1b_InFrameDel_T63_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN0Mx_WT_T18_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN1M0_WT_T42_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2bN1M0_WT_T477_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_Frame_Shift_Del_T315_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T111_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T12_69yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T167_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T17_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T208_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T330_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T340_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T467_56yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T60_77yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_InFrameDel_T64_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_MissenseMutation_T325_76yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_MissenseMutation_T349_73yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_MissenseMutation_T53_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_MissenseMutation_T56_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_MissenseMutation_T57_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T114_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T124_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T137_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T279_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T318_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T334_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T373_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T375_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T43_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T47_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T574_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T578_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T685_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M0_WT_T717_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M1b_MissenseMutation_T608_50yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0M1b_WT_T185_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN0Mx_InFrameDel_T410_80yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN1M0_WT_T585_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN1M1b_InFrameDel_T211_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2cN1M1b_WT_T491_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2N0M0_MissenseMutation_T508_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2N0M0_WT_T178_65yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2N0M0_WT_T502_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T2N0M0_WT_T546_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_FrameShiftDel_T85_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_InFrameDel_T113_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_InFrameDel_T300_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_InFrameDel_T728_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_MissenseMutation_T1_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_WT_T172_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_WT_T268_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_WT_T389_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_WT_T61_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN0M0_WT_T72_72yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN1M0_WT_T201_55yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN1M0_WT_T217_79yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aN1M1a_WT_T69_75yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3aNXM0_InFrameDel_T31_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN0M0_MissenseMutation_T139_78yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN0M0_WT_T103_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN0M0_WT_T496_66yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN0M0_WT_T605_70yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN0M1b_InFrameDel_T174_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN0M1b_WT_T502_62yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN1M0_WT_T125_74yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN1M0_WT_T286_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN1M0_WT_T342_71yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN1M0_WT_T67_51yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN1M1a_Frame_Shift_Del_T28_68yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bN1M1c_WT_T166_67yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bNAM0_WT_T637_57yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3bNxM0_WT_T729_64yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3cN0M0_WT_T71_61yrs_Male.bed.gz
wget https://download.cncb.ac.cn/methbank/MethBank4.0/Single-base_Resolution_Methylomes/Homo_sapiens/Methylomes/BED/Hom_Tumor_Prostate_T3NAM0_WT_T638_69yrs_Male.bed.gz
